name: Build and Test
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  call-build-and-test-workflow:
    uses: roland-burke/workflows/.github/workflows/build-and-test-go.yml@master
